In [6]:
import numpy as np
import pandas as pd

In [66]:
df = pd.read_csv("Countries.csv")

In [77]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)

In [79]:
df

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,forest_area,land_area,rural_land,urban_land,central_government_debt_pct_gdp,expense_pct_gdp,gdp,inflation,self_employed_pct,tax_revenue_pct_gdp,unemployment_pct,vulnerable_employment_pct,electricity_access_pct,alternative_nuclear_energy_pct,electricty_production_coal_pct,electricty_production_hydroelectric_pct,electricty_production_gas_pct,electricty_production_nuclear_pct,electricty_production_oil_pct,electricty_production_renewable_pct,energy_imports_pct,fossil_energy_consumption_pct,renewable_energy_consumption_pct,co2_emissions,methane_emissions,nitrous_oxide_emissions,greenhouse_other_emissions,urban_population_under_5m,health_expenditure_pct_gdp,health_expenditure_capita,hospital_beds,hiv_incidence,suicide_rate,armed_forces,internally_displaced_persons,military_expenditure_pct_gdp,birth_rate,death_rate,fertility_rate,internet_pct,life_expectancy,net_migration,population_female,population_male,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
0,Afghanistan,Islamic State of Afghanistan,Afghan afghani,Kabul,Southern Asia,Asia,Afghan,33.000000,65.000000,383560.00,12084.4,6.522300e+05,6.361730e+05,3993.84000,NaN,39.220100,1.458310e+10,2.302370,84.33390,9.898450,11.710,82.690700,97.70000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.86,8.709470e+03,1.622200e+04,4863.390000,-1800.00000,0.000000,16.82610,81.3198,0.3900,0.04,4.1,278000.0,4394000.0,1.358860,35.842,7.344,4.643,18.40000,62.0,-183672,20362329,20766442,41128771,27.01610,30181937,10946834,2.14,2.97,Authoritarian,12.9,Ashraf Ghani,President
1,Albania,Republic of Albania,Albanian lek,Tirana,Southern Europe,Europe,Albanian,41.000000,20.000000,11655.50,7889.0,2.740000e+04,2.733160e+04,827.69400,82.38360,24.536300,1.888210e+10,6.725200,53.04550,18.198600,11.808,50.062400,100.00000,24.548000,0.000000,100.000000,0.000000,0.000000,0.000000,0.000000,13.79800,61.42180,44.58,4.383200e+03,2.692200e+03,1015.190000,11.68140,6.367260,6.65959,350.8350,2.8900,0.03,4.3,8000.0,NaN,1.415640,10.240,11.325,1.390,79.32000,76.0,-10612,1391085,1384548,2775634,35.71430,1004807,1770827,2.62,5.98,Hybrid regime,33.7,Edi Rama,Prime Minister
2,Algeria,People's Democratic Republic of Algeria,Algerian dinar,Algiers,Northern Africa,Africa,Algerian,28.000000,3.000000,413588.00,19490.0,2.381740e+06,2.305480e+06,9357.10000,NaN,NaN,1.919130e+11,9.265520,30.52590,NaN,11.550,26.071200,99.78780,0.030106,0.000000,0.210762,98.357500,0.000000,1.319810,0.111922,-177.12400,99.97790,0.15,1.615630e+05,8.654390e+04,12578.700000,-7720.56000,1.124750,6.32118,214.8520,1.9000,0.04,2.5,317000.0,2500.0,5.592580,21.524,4.546,2.889,70.77000,76.0,-18797,22040987,22862237,44903225,8.10811,11328186,33575039,1.71,3.50,Authoritarian,24.0,Abdelmadjid Tebboune,President
3,Andorra,Principality of Andorra,Euro,Andorra la Vella,Southern Europe,Europe,Andorran,42.500000,1.500000,187.20,160.0,4.700000e+02,4.094970e+02,30.93580,NaN,NaN,3.352030e+09,NaN,NaN,NaN,NaN,NaN,100.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20.59,4.488840e+02,5.360100e+01,1.758810,NaN,0.000000,9.05176,3336.9200,2.5000,NaN,NaN,NaN,NaN,NaN,7.000,3.900,1.270,93.89750,NaN,1377,39038,40786,79824,46.42860,9730,70094,3.17,0.00,Unknown,38.9,Xavier Espot Zamora,Head of Government
4,Angola,People's Republic of Angola,Angolan kwanza,Luanda,Middle Africa,Africa,Angolan,-12.500000,18.500000,569525.00,666074.0,1.246700e+06,1.251000e+06,2991.35000,NaN,16.685000,1.067140e+11,25.754300,65.85220,10.090400,10.209,61.325200,48.22390,2.548840,0.000000,53.174900,0.000000,0.000000,46.825100,0.000000,-540.99700,48.30560,61.02,1.981450e+04,3.270320e+04,17757.900000,5203.07000,1.220310,2.91183,50.7426,0.8000,0.52,6.1,117000.0,NaN,1.132060,38.809,8.009,5.304,32.60230,62.0,29089,17998220,17590767,35588987,33.63640,11359649,24229338,2.24,3.62,Authoritarian,12.4,João Lourenço,President
5,Antigua and Barbuda,Antigua and Barbuda,East Caribbean dollar,Saint John's,Caribbean,Americas,Antiguan,17.050000,-61.800000,90.00,81.2,4.400000e+02,3.963350e+02,31.86330,NaN,NaN,1.757600e+09,7.531080,NaN,NaN,NaN,NaN,100.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00000,0.72,4.746000e+02,2.048660e+02,11.763500,471.23700,3.976560,5.61473,830.3400,2.8900,NaN,0.4,0.0,NaN,NaN,12.115,6.365,1.580,95.66340,78.0,0,48981,44782,93763,11.11110,70935,22828,0.00,0.00,Unknown,31.1,Gaston Browne,Prime Minister
6,Argentina,Argentine Republic,Argentine peso,Buenos Aires,South America,Americas,Argentine,-34.000000,-64.000000,1083820.00,285730.0,2.736690e+06,2.735390e+06,11432.70000,NaN,22.865600,6.327700e+11,NaN,28.60180,11.484400,6.491,25.463300,100.00000,5.501500,2.029570,26.241600,49.482300,4.166730,15.423200,1.898490,13.02940,87.72240,9.84,1.545360e+05,1.310360e+05,51061.500000,3701.73000,0.896205,9.98438,863.7140,4.9900,0.11,8.4,103000.0,NaN,0.565318,13.902,8.955,1.885,87.15070,75.0,2344,23345532,22889298,46234830,44.74710,3538352,42696478,2.76,7.02,Flawed democracy,27.6,Alberto Fernández,President
7,Armenia,Republic of Armenia,Armenian dram,Yerevan,Western Asia,Asia,Armenian,40.000000,45.000000,16760.00,3284.7,2.847000e+04,2.734220e+04,922.33500,60.15620,25.000000,1.950280e+10,8.640910,30.56910,22.028800,12.557,29.065800,100.00000,25.718300,0.000000,28.285700,35.914900,31.806500,0.000000,0.051289,71.34130,74.56190,8.38,6.746600e+03,2.319920e+03,1173.580000,722.15500,0.000000,12.24100,551.5430,4.2000,NaN,3.3,49000.0,8400.0,4.440120,12.049,13.007,1.575,78.61230,72.0,-12825,1530390,1250079,2780469,35.51400,1012841,1767628,2.70,4.79,Hybrid regime,30.8,Nikol Pashinyan,Prime Minister
8,Australia,Commonwealth of Australia,Australian dollar,Canberra,Australia and New Zealand,Oceania,Australian,-27.000000,133.000000,3557750.00,1340050.0,7.692020e+06,7.650420e+06,11946.00000,70.17640,32.718900,1.675420e+12,6.594100,16.60160,23.127500,3.661,10.756700,100.00000,2.154390,62.871600,5.296180,20.795500,0.000000,2.695060,8.341660,-190.19100,89.62560,10.89,3.789970e+05,1.314850e+05,49331.800000,-17268.70000,2.709680,10.64900,5901.1100,3.8400,0.02,12.5,59000.0,NaN,1.978420,12.100,6.700,1.700,96.24000,83.0,117929,13079142,12899794,25978935,38.41060,3510274,22468661,4.73,9.09,Full democracy,33.3,Anthony Albanese,Prime Minister
9,Austria,Republic of Austria,Euro,Vienna,Western Europe,Europe,Austrian,47.333333,13.333333,26467.60,38991.5,8.252000e+04,8.003090e+04,2973.71000,94.32100,49.971500,4.714000e+11,8.546870,11.75630,25.783000,4.707,7.482760,100.00000,12.212900,8.226610,59.997100,12.601400,0.000000,1.394040,16.493700,63.54490,65.66180,35.77,5.914240e+04,6.863080e+03,3759.740000,-8604.11000,0.000000,12.17360,6491.1200,7.2700,NaN,14.6,22000.0,NaN,0.802122,9.600,10.300,1.480,92.52920,81.0,20314,4590655,4451873,9042528,40.98360,3684288,5358240,5.10,8.29,Full democracy,39.0,Sebastian Kurz,Federal Chancellor
10,Azerbaijan,Republic of Azerbaijan,New Azeri manat,Baku,Western Asia,Asia,Azerbaijani,40.500000,47.500000,47801.00,11317.7,8.264600e+04,8.221870e+04,2589.86000,16.82240,27.144400,7.872110e+10,13.852300,66.28430,13.421300,5.462,54.464200,100.00000,0.572046,0.000000,6.630750,86.082300,0.000000,6.509240,0.409106,-310.38500,98.36600,1.23,3.430500e+04,1.573310e+04,4793.550000,-514.23500,0.000000,4.60677,191.2270,4.8200,0.03,4.1,82000.0,659000.0,5.270060,11.100,7.600,1.520,86.00000,69.0,1084,5154492,5020523,10175016,18.33330,4357959,5817057,1.32,2.65,Authoritarian,27.9,Ilham Aliyev,President
11,Bahrain,Kingdom of Bahrain,Bahraini dinar,Manama,Western Asia,Asia,Bahraini,26.000000,50.550000,86.00,7.0,7.850000e+02,3.357070e+02,330.29200,29.39860,20.176100,4.439080e+10,3.625740,2.61064,4.216840,1.399,1.048280,100.00000,0.000000,0.000000,0.000000,99.968400,0.000000,0.031597,0.000000,-61.58430,99.36580,0.00,3.247020e+04,1.764140e+04,171.638000,8391.62000,31.981700,4.72300,1110.0000,1.7400,0.05,8.9,19000.0,NaN,3.558260,11.926,2.479,1.811,100.00000,79.0,-9150,560034,912199,1472233,20.00000,151007,1321226,1.28,2.71,Authoritarian,29.2,Sheikh Hamad bin Isa Al Khalifa,King
12,Bangladesh,People's Republic of Bangladesh,Bangladeshi taka,Dhaka,Southern Asia,Asia,Bangladeshi,24.000000,90.000000,99010.00,18834.0,1.301700e+05,7.932890e+04,56970.00000,31.20450,8.324250,4.602010e+11,7.696950,59.03190,7.642360,4.699,53.673800,98.99100,0.153500,1.689520,0.959143,80.703600,0.000000,16.380000,0.267747,16.84170,73.76890,27.96,8.549310e+04,8.890400e+04,28076.800000,1513.77000,6.064840,2.62801,50.6641,0.7900,0.01,3.7,227000.0,427000.0,1.269780,17.821,5.680,1.981,38.91740,72.0,-174500,86327159,84859213,171186372,20.85710,103206552,67979820,1.54,5.57,Hybrid regime,22.7,Sheikh Hasina,Prime Minister
13,Barbados,Barbados,Barbados dollar,Bridgetown,Caribbean,Americas,Barbadian,13.166667,-59.533333,100.00,63.0,4.300000e+02,2.485270e+02,187.58800,146.92700,33.805000,5.637910e+09,4.100290,19.21920,27.478500,8.203,18.707400,100.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00000,4.68,1.096070e+03,2.359570e+03,38.478700,-101.44700,1.846750,7.20014,1199.7100,5.9700,0.24,0.6,1000.0,NaN,NaN,10.832,9.007,1.633,85.82000,78.0,-28,146550,135084,281635,26.66670,193416,88219,0.00,0.00,Unknown,35.2,Mia Mottley,Prime Minister
14,Belarus,Republic of Belarus,Belarusian rubel,Minsk,Eastern Europe,Europe,Belarusian,53.000000,28.000000,82810.00,87676.0,2.029800e+05,2.014560e+05,2882.60000,33.24420,29.928100,7.279350e+10,15.209700,3.77292,12.022900,4.170,2.945080,100.00000,0.053921,0.000000,0.313949,97.866900,0.000000,1.062140,0.501731,86.77970,92.44040,8.39,5.480150e+04,1.707930e+04,15902.500000,-7365.67000,0.000000,6.40607,408.0950,10.8300,0.12,21.2,155000.0,NaN,1.155810,9.283,16.544,1.483,86.89000,72.0,12961,4968656,4240046,9208701,40.00000,1811720,7396981,1.51,3.13,Authoritarian,36.5,Alexander Lukashenko,President
15,Belgium,Kingdom of Belgium,Euro,Brussels,Western Europe,Europe,Belgian,50.833333,4.000000,13646.10,6893.0,3.028000e+04,2.278050e+04,7730.88000,109.22400,41.698800,5.786040e+11,9.597510,14.01490,23.349500,5.631,10.701400,100.00000,15.110300,6.108010,0.457238,32.806100,37.532400,0.300512,20.342800,80.09180,75.87080,12.28,8.536410e+04,7.974090e+03,4564.200000,2697.19000,4.232880,11.06450,5009.4600,5.5800,NaN,18.3,26000.0,NaN,1.081810,10.200,9.700,1.600,92.79000,82.0,52356,5903468,5765978,11669446,42.66670,215535,11453911,6.48,7.78,Flawed democracy,37.1,Sophie Wilmès,Prime Minister
16,Belize,Belize,Belize dollar,Belmopan,Central America,Americas,Belizean,17.250000,-88.750000,1720.00,12770.5,2.281000e+04,2.170840e+04,122.90000,61.03770,22.148600,2.824080e+09,3.235640,35.88710,21.160200,9.687,30.949200,97.69210,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00000,31.35,6.876000e+02,5.140450e+02,205.409000,-344.10500,28.469200,6.92426,277.9900,1.0400,0.42,7.1,2000.0,NaN,1.253580,17.976,6.353,2.010,61.99420,70.0,577,201525,203747,405272,12.50000,217242,188030,2.84,0.00,Unknown,21.6,Dean Barrow,Prime Minister
17,Benin,Republic of Benin,West African CFA franc,Porto-Novo,Western Africa,Africa,Beninese,9.500000,2.250000,39500.00,31351.5,1.127600e+05,1.136910e+05,2005.91000,NaN,NaN,1.740170e+10,1.350780,89.83140,10.789100,1.654,88.405200,41.97360,0.000000,0.000000,4.093570,0.000000,0.000000,94.444400,1.461990,46.59070,36.72460,46.20,7.980400e+03,4.029620e+03,3007.640000,1486.29000,6.003200,2.58937,32.1271,0.5000,0.14,7.8,12000.0,1200.0,0.560621,36.608,9.434,4.973,33.96530,60.0,1732,6663569,6689295,13352864,7.40741,6738656,6614208,2.46,5.74,Hybrid regime,13.6,Patrice Talon,President
18,Bhutan,Kingdom of Bhutan,Bhutanese ngultrum,Thimphu,Southern Asia,Asia,Bhutanese,27.500000,90.500000,5130.00,27250.8,3.814000e+04,3.904070e+04,28.60280,117.33000,25.447300,2.539550e+09,5.639170,73.05670,12.984200,3.604,72.956800,100.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00000,87.45,1.035200e+03,4.515240e+02,97.265400,-422.10000,0.000000,4.37175,133.7030,1.7400,0.10,4.6,6000.0,NaN,NaN,12.482,6.477,1.413,85.63690,72.0,291,368525,413930,782455,17.39130,440632,341823,2.62,5.30,Hybrid regime,24.8,Lotay Tshering,Prime Minister
19,Bolivia,Plurinational State of Bolivia,Bolivian Boliviano,Sucre,South America,Americas,Bolivian,-17.000000,-65.000000,377870.00,508338.0,1.083300e+06,1.059510e+06,1767.52000,68.33990,21.811000,4.306890e+10,1.746330,69.11600,16.964900,4.419,66.023100,98.55620,1.974980,0.000000,28.881300,66.346200,0.000000,2.251410,2.521110,-177.98600,84.15330,16.86,1.837530e+04,2.659780e+04,9838.140000,2436.27000,0.000000,7.85706,241.1180,1.2900,0.13,6.2,71000.0,31.0,1.544460,21.836,9.945,2.618,65.97740,64.0,-4666,6097747,6126364,12224110,46.15380,3565773,8658337,2.21,5.70,Hybrid regime,20.1,Jeanine Áñez,President
20,Bosnia and Herzegovina,Bosnia and Herzegovina,Bosnia and Herzegovina convertible mark,Sarajevo,Southern Europe,Europe,Bosnian,44.000000,18.000000,22160.00,21879.1,5.120000e+04,4.913470e+04,1641.93000,47.02080,34.893000,2.452750e+10,14.020800,17.97510,19.116800,14.053,12.262900,100.00000,4.273870,63.977200,35.517300,0.191951,0.000000,0.313520,0.000000,22.73010,77.52200,37.71,2.094680e+04,3.660950e+03,1283.700000,-3144.12000,0.000000,9.84113,591.4060,3.4900,NaN,10.9,11000.0,91000.0,0.894938,8.420,15.712,1.350,75.67620,75.0,-25865,1641713,1591814,3233526,16.66670,1621904,1611622,2.69,4.98,Hybrid regime,38.1,Valentin Inzko,High Representative
21,Botswana,Republic of Botswana,Botswana pula,Gaborone,Southern Africa,Africa,Motswana,-22.000000,24.000000,258620.00,152547.0,5.667300e+05,5.728870e+05,804.34600,19.61610,28.409300,2.035230e+10,11.665600,28.27060,22.246000,20.684,26.013500,73.72590,0.003166,96.360000,0.000000,0.000000,0.000000,3.606340,0.033704,44.50000,74.68800,27.21,5.763690e+03,3.434490e+03,2963.630000,841.57100,0.000000,6.18665,362.7350,1.8000,3.48,16.1,9000.0,NaN,2.859640,23.576,9.461,2.791,73.50000,61.0,1816,1331489,1298807,2630296,11.11110,730591,1899705,3.12,7.81,Flawed democracy,19.7,Mokgweetsi Masisi,President
22,Brazil,Federative Republic of Brazil,Brazilian real,Brasília,South America,Americas,Brazilian,-10.000000,-55.000000,2368790.00,4966200.0,8.358140e+06,8.385500e+06,45853.30000,86.09500,32.199100,1.920100e+12,9.280110,35.08680,14.316800,9.461,30.682300,99.46210,10.809100,4.722410,61.848500,13.666200,2.603570,5.044250,12.118400,11.87010,59.10750,50.05,4.141390e+05,4.492140e+05,191103.000000,-12454.90000,1.741760,10.31290,700.7130,2.0900,0.24,6.9,762000.0,5600.0,1.190810,12.883,8.326,1.641,80.69000,73.0,20376,109580471,105733027,215313498,17.73880,26795765,188517733,2.38,6.97,Flawed democracy,29.2,Jair Bolsonaro,President
23,Brunei,Brunei Darussalam,Brunei dollar,Bandar Seri Begawan,South-Eastern Asia,Asia,Bruneian,4.500000,114.666667,134.00,3800.0,5.270000e+03,5.571880e+03,199.17200,NaN,NaN,1.668150e+10,3.682250,9.08590,NaN,7.203,6.549670,100.00000,0.004840,0.000000,0.000000,98.952400,0.000000,1.000000,0.047619,-357.39400,99.99520,0.01,9.588000e+03,1.538870e+03,137.896000,-902.12600,13.937500,2.39378,650.4780,2.8500,NaN,2.7,8000.0,NaN,3.262230,13.800,5.211,1.778,98.08000,75.0,-192,216797,232205,449002,9.09091,94946,354056,1.52,0.00,Unknown,28.2,Hassanal Bolkiah,Sultan and Prime Minister
24,Bulgaria,Republic of Bulgaria,Bulgarian lev,Sofia,Eastern Europe,Europe,Bulgarian,43.000000,25.000000,50470.00,38930.0,1.085600e+05,1.089140e+05,2109.34000,32.80990,36.369800,8.904040e+10,15.325300,10.47510,20.621300,4.402,7.022220,99.80000,25.825700,46.206600,11.614200,3.824220,33.812100,0.373395,6.374380,36.55080,71.04590,21.08,3.413810e+04,6.980500e+03,4328.730000,-7702.91000,1.185940,8.52064,856.7050,7.4500,0.03,9.7,37000.0,NaN,1.594890,8.500,21.700,1.580,75.27140,72.0,-8716,3329964,3135133,6465097,24.16670,1528155,4936942,2.23,7.03,Flawed democracy,40.7,Boyko Borisov,Prime Minister
25,Burkina Faso,Burkina Faso,West African CFA franc,Ouagadougou,Western Africa,Africa,Burkinabe,13.000000,-2.000000,121430.00,62164.0,2.736000e+05,2.739180e+05,1599.30000,55.46930,18.143500,1.888460e+10,14.290200,87.09170,15.906500,5.175,86.460000,18.95070,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,68.00,5.456700e+03,1.540830e+04,10060.700000,2087.93000,0.000000,6.71933,54.1770,0.4000,0.08,7.5,11000.0,1882000.0,2.891130,35.541,8.958,4.772,21.57980,59.0,-13097,11374607,11299155,22673762,16.90140,15446047,7227715,3.19,4.75,Hybrid regime,12.9,Roch Marc Christian Kaboré,President
26,Burundi,Republic of Burundi,Burundi franc,Bujumbura,Eastern Africa,Africa,Burundian,-3.500000,30.000000,20330.00,2796.4,2.568000e+04,2.415060e+04,887.84200,162.56100,20.647600,3.073410e+09,18.800900,88.18570,13.597400,1.020,86.921700,10.23380,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,83.25,7.134660e+02,1.258190e+03,1636.390000,-293.61800,0.000000,6.50142,16.4202,0.7900,0.14,6.2,51000.0,8500.0,1.922800,34.842,7.474,5.078,5.80492,62.0,-14415,6488650,6400926,12889576,38.21140,11031286,1858290,1.48,2.33,Authoritarian,11.9,Pierre Nkurunziza,President
27,Cabo Verde,Republic of Cabo Verde,Cabo Verde escudo,Praia,Western Africa,Africa,Cape Verdian,16.000000,-24.000000,790.00,457.2,4.030000e+03,4.043850e+03,59.55430,NaN,25.194000,2.314820e+09,1.862150,31.26440,17.803600,13.570,27.055800,95.52140,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00000,23.24,6.206000e+02,9.320760e+01,59.475600,460.31300,1.016860,6.01976,176.0240,2.1000,0.24,12.9,1000.0,NaN,0.535772,16.951,6.028,1.896,69.76230,74.0,-1274,298239,294911,593149,38.88890,192507,400642,3.95,7.88,Flawed democracy,22.9,NaN,NaN
28,Cambodia,Kingdom of Cambodia,Cambodian riel,Phnom Penh,South-Eastern Asia,Asia,Cambodian,13.000000,105.000000,57890.00,80683.7,1.765200e+05,1.761810e+05,1838.75000,NaN,18.448000,2.995680e+10,5.343700,47.16620,16.364900,0.361,47.045800,82.50170,3.319270,48.396600,45.485600,0.000000,0.000000,5.185350,0.932454,33.11630,30.62910,51.41,1.865280e+04,1.783640e+04,4784.590000,3983.04000,0.687841,7.50527,115.7650,0.9000,0.07,4.9,191000.0,NaN,2.316360,19.334,6.838,2.344,60.15240,70.0,-24262,8468316,8299527,16767842,20.80000,12556766,4211076,1.70,3.59,Authoritarian,22.7,Hun Sen,Prime Minister
29,Cameroon,Republic of Cameroon,Central African CFA franc,Yaoundé,Middle Africa,Africa,Cameroonian,6.000000,12.000000,97500.00,203405.0,4.727100e+05,4.638370e+05,2352.11000,79.45770,12.060300,4.434160e+10,6.247680,75.23600,10.870600,4.001,72.325800,65.44670,4.600760,0.000000,74.992600,5.992900,0.000000,17.889900,1.124590,-28.31980,38.31790,78.94,9.928400e+03,1.779770e+04,62399.500000,1385.67000,1.916620,3.76583,58.0053,1.3000,0.56,9.0,34000.0,987000.0,1.024090,34.938,8.582,4.463,45.60220,60.0,-9889,13992014,13922522,27914536,33.88890,11519492,16395044,1.81,3.28,Authoritarian,13.6,Paul Biya,President
30,Canada,Canada,Canadian dollar,Ottawa,Northern America,Americas,Canadian,60.000000,-95.000000,577430.00,3469280.0,8.965590e+06,9.197140e+06,13983.10000,64.04010,22.733400,2.139840e+12,6.802800,14.34100,13.259400,5.209,10.343800,100.00000,19.770800,9.836450,56.744200,10.016000,15.546600,1.214780,6.267260,-72.52820,74.08910,23.85,5.168740e+05,1.001430e+05,47080.300000,-112199.00000,0.892721,11.67880,6086.0800,2.5200,NaN,11.8,72000.0,NaN,1.315150,9.600,7.800,1.430,92.83400,83.0,195181,19583244,19346659,38929902,30.47340,7103929,31825973,4.98,9.15,Full democracy,36.4,Justin Trudeau,Prime Minister
31,Central African Republic,Central African Republic,Central African CFA franc,Bangui,Middle Africa,Africa,Central African,7.000000,21.000000,50800.00,223030.0,6.229800e+05,6.221650e+05,535.37600,NaN,11.661400,2.382620e+09,5.583170,94.46140,8.206290,6.363,93.634000,15.68030,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90.45,2.366000e+02,1.010850e+04,10628.600000,-203.22900,0.000000,9.40207,41.9605,1.0000,0.58,12.3,10000.0,516000.0,1.858680,42.680,11.393,5.978,10.58260,54.0,-85860,2790791,2788352,5579144,12.85710,3173417,2405727,1.65,1.52,Authoritarian,10.8,Faustin-Archange Touadéra,President

In [68]:
df[['population','country']].max()

population    1417173173
country         Zimbabwe
dtype: object

In [69]:
df[['country','population']].min()

country       Afghanistan
population          11312
dtype: object

In [70]:
df[['population','capital_city']].max()

population      1417173173
capital_city        Zagreb
dtype: object

In [71]:
df[['democracy_score','country']].sort_values(by='democracy_score' , ascending=False).head()

     democracy_score      country
127             9.87       Norway
74              9.58      Iceland
164             9.39       Sweden
122             9.26  New Zealand
46              9.22      Denmark

In [72]:
df['region'].nunique()

22

In [73]:
df[df['region'] == 'Southern Europe']['country'].count()

np.int64(15)

In [74]:
df_sorted = df[['population','country','political_leader']].sort_values(by='population',ascending=False)

In [75]:
df_sorted.iloc[2][['country','political_leader','population']]

country             United States
political_leader        Joe Biden
population              333287557
Name: 184, dtype: object

In [76]:
df[df['political_leader'].isnull()]['country']

27                         Cabo Verde
151                   Slovak Republic
159               St. Kitts and Nevis
160                         St. Lucia
161    St. Vincent and the Grenadines
172                       Timor-Leste
190                West Bank and Gaza
Name: country, dtype: object

In [83]:
df[df['country_long'].str.contains('Republic', na=False)].shape[0]

125

In [92]:
df[df['region'].str.contains('Africa')]#.sort_values(by='population', ascending=False).iloc[0][['country','population']]

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,forest_area,land_area,rural_land,urban_land,central_government_debt_pct_gdp,expense_pct_gdp,gdp,inflation,self_employed_pct,tax_revenue_pct_gdp,unemployment_pct,vulnerable_employment_pct,electricity_access_pct,alternative_nuclear_energy_pct,electricty_production_coal_pct,electricty_production_hydroelectric_pct,electricty_production_gas_pct,electricty_production_nuclear_pct,electricty_production_oil_pct,electricty_production_renewable_pct,energy_imports_pct,fossil_energy_consumption_pct,renewable_energy_consumption_pct,co2_emissions,methane_emissions,nitrous_oxide_emissions,greenhouse_other_emissions,urban_population_under_5m,health_expenditure_pct_gdp,health_expenditure_capita,hospital_beds,hiv_incidence,suicide_rate,armed_forces,internally_displaced_persons,military_expenditure_pct_gdp,birth_rate,death_rate,fertility_rate,internet_pct,life_expectancy,net_migration,population_female,population_male,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
2,Algeria,People's Democratic Republic of Algeria,Algerian dinar,Algiers,Northern Africa,Africa,Algerian,28.000000,3.000000,413588.0,19490.0,2381740.0,2305480.000,9357.1000,NaN,NaN,1.919130e+11,9.26552,30.5259,NaN,11.550,26.0712,99.78780,0.030106,0.000000,0.210762,98.357500,0.0000,1.319810,0.111922,-177.12400,99.97790,0.15,161563.000,86543.9000,12578.70000,-7720.5600,1.124750,6.32118,214.8520,1.90,0.04,2.5,317000.0,2500.0,5.592580,21.524,4.546,2.889,70.77000,76.0,-18797,22040987,22862237,44903225,8.10811,11328186,33575039,1.71,3.50,Authoritarian,24.0,Abdelmadjid Tebboune,President
4,Angola,People's Republic of Angola,Angolan kwanza,Luanda,Middle Africa,Africa,Angolan,-12.500000,18.500000,569525.0,666074.0,1246700.0,1251000.000,2991.3500,NaN,16.685000,1.067140e+11,25.75430,65.8522,10.090400,10.209,61.3252,48.22390,2.548840,0.000000,53.174900,0.000000,0.0000,46.825100,0.000000,-540.99700,48.30560,61.02,19814.500,32703.2000,17757.90000,5203.0700,1.220310,2.91183,50.7426,0.80,0.52,6.1,117000.0,NaN,1.132060,38.809,8.009,5.304,32.60230,62.0,29089,17998220,17590767,35588987,33.63640,11359649,24229338,2.24,3.62,Authoritarian,12.4,João Lourenço,President
17,Benin,Republic of Benin,West African CFA franc,Porto-Novo,Western Africa,Africa,Beninese,9.500000,2.250000,39500.0,31351.5,112760.0,113691.000,2005.9100,NaN,NaN,1.740170e+10,1.35078,89.8314,10.789100,1.654,88.4052,41.97360,0.000000,0.000000,4.093570,0.000000,0.0000,94.444400,1.461990,46.59070,36.72460,46.20,7980.400,4029.6200,3007.64000,1486.2900,6.003200,2.58937,32.1271,0.50,0.14,7.8,12000.0,1200.0,0.560621,36.608,9.434,4.973,33.96530,60.0,1732,6663569,6689295,13352864,7.40741,6738656,6614208,2.46,5.74,Hybrid regime,13.6,Patrice Talon,President
21,Botswana,Republic of Botswana,Botswana pula,Gaborone,Southern Africa,Africa,Motswana,-22.000000,24.000000,258620.0,152547.0,566730.0,572887.000,804.3460,19.61610,28.409300,2.035230e+10,11.66560,28.2706,22.246000,20.684,26.0135,73.72590,0.003166,96.360000,0.000000,0.000000,0.0000,3.606340,0.033704,44.50000,74.68800,27.21,5763.690,3434.4900,2963.63000,841.5710,0.000000,6.18665,362.7350,1.80,3.48,16.1,9000.0,NaN,2.859640,23.576,9.461,2.791,73.50000,61.0,1816,1331489,1298807,2630296,11.11110,730591,1899705,3.12,7.81,Flawed democracy,19.7,Mokgweetsi Masisi,President
25,Burkina Faso,Burkina Faso,West African CFA franc,Ouagadougou,Western Africa,Africa,Burkinabe,13.000000,-2.000000,121430.0,62164.0,273600.0,273918.000,1599.3000,55.46930,18.143500,1.888460e+10,14.29020,87.0917,15.906500,5.175,86.4600,18.95070,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,68.00,5456.700,15408.3000,10060.70000,2087.9300,0.000000,6.71933,54.1770,0.40,0.08,7.5,11000.0,1882000.0,2.891130,35.541,8.958,4.772,21.57980,59.0,-13097,11374607,11299155,22673762,16.90140,15446047,7227715,3.19,4.75,Hybrid regime,12.9,Roch Marc Christian Kaboré,President
26,Burundi,Republic of Burundi,Burundi franc,Bujumbura,Eastern Africa,Africa,Burundian,-3.500000,30.000000,20330.0,2796.4,25680.0,24150.600,887.8420,162.56100,20.647600,3.073410e+09,18.80090,88.1857,13.597400,1.020,86.9217,10.23380,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,83.25,713.466,1258.1900,1636.39000,-293.6180,0.000000,6.50142,16.4202,0.79,0.14,6.2,51000.0,8500.0,1.922800,34.842,7.474,5.078,5.80492,62.0,-14415,6488650,6400926,12889576,38.21140,11031286,1858290,1.48,2.33,Authoritarian,11.9,Pierre Nkurunziza,President
27,Cabo Verde,Republic of Cabo Verde,Cabo Verde escudo,Praia,Western Africa,Africa,Cape Verdian,16.000000,-24.000000,790.0,457.2,4030.0,4043.850,59.5543,NaN,25.194000,2.314820e+09,1.86215,31.2644,17.803600,13.570,27.0558,95.52140,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00000,23.24,620.600,93.2076,59.47560,460.3130,1.016860,6.01976,176.0240,2.10,0.24,12.9,1000.0,NaN,0.535772,16.951,6.028,1.896,69.76230,74.0,-1274,298239,294911,593149,38.88890,192507,400642,3.95,7.88,Flawed democracy,22.9,NaN,NaN
29,Cameroon,Republic of Cameroon,Central African CFA franc,Yaoundé,Middle Africa,Africa,Cameroonian,6.000000,12.000000,97500.0,203405.0,472710.0,463837.000,2352.1100,79.45770,12.060300,4.434160e+10,6.24768,75.2360,10.870600,4.001,72.3258,65.44670,4.600760,0.000000,74.992600,5.992900,0.0000,17.889900,1.124590,-28.31980,38.31790,78.94,9928.400,17797.7000,62399.50000,1385.6700,1.916620,3.76583,58.0053,1.30,0.56,9.0,34000.0,987000.0,1.024090,34.938,8.582,4.463,45.60220,60.0,-9889,13992014,13922522,27914536,33.88890,11519492,16395044,1.81,3.28,Authoritarian,13.6,Paul Biya,President
31,Central African Republic,Central African Republic,Central African CFA franc,Bangui,Middle Africa,Africa,Central African,7.000000,21.000000,50800.0,223030.0,622980.0,622165.000,535.3760,NaN,11.661400,2.382620e+09,5.58317,94.4614,8.206290,6.363,93.6340,15.68030,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90.45,236.600,10108.5000,10628.60000,-203.2290,0.000000,9.40207,41.9605,1.00,0.58,12.3,10000.0,516000.0,1.858680,42.680,11.393,5.978,10.58260,54.0,-85860,2790791,2788352,5579144,12.85710,3173417,2405727,1.65,1.52,Authoritarian,10.8,Faustin-Archange Touadéra,President
32,Chad,Republic of Chad,Central African CFA franc,N'Djamena,Middle Africa,Africa,Chadian,15.000000,19.000000,502380.0,43130.0,1259200.0,1272920.000,948.8240,NaN,NaN,1.270410e+10,5.78803,91.9565,NaN,1.412,90.6055,11.26860,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,73.74,1568.400,59438.9000,27724.60000,-70.9411,0.000000,5.40749,34.8013,0.40,0.21,6.4,45000.0,300000.0,2.794140,43.357,12.504,6.255,17.86890,53.0,9016,8827313,8896002,17723315,25.88830,13458554,4264761,2.13,1.61,Authoritarian,11.2,Idriss Déby,President
36,Comoros,Union of the Comoros,Comorian franc,Moroni,Eastern Africa,Africa,Comoran,-12.166667,44.250000,1310.0,329.2,1861.0,1534.770,142.5340,NaN,NaN,1.242520e+09,-4.29487,58.7802,NaN,8.811,57.8390,87.94260,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00000,39.05,328.200,236.8180,46.81580,101.5780,2.147650,5.34623,80.8244,2.16,0.01,5.4,NaN,NaN,NaN,29.398,8.718,3.978,27.33690,63.0,-1772,416416,420357,836774,16.66670,586880,249894,2.80,3.71,Authoritarian,16.3,Azali Assoumani,President
37,Congo,Republic of Congo,Central African CFA franc,Brazzaville,Middle Africa,Africa,Congolese,-1.000000,15.000000,106280.0,219460.0,341500.0,340341.000,420.2630,25.48270,19.467900,1.461550e+10,3.04344,76.2354,9.107080,21.795,75.2794,49.65720,1.428710,0.000000,53.344900,46.655100,0.0000,0.000000,0.000000,-496.59800,40.48060,71.88,7153.900,9957.2600,1610.02000,-1372.3000,0.711295,4.46762,80.8084,1.60,2.39,6.5,0.0,27000.0,2.912710,30.691,7.063,4.171,8.65000,64.0,-4466,2988624,2981800,5970424,14.56950,1866593,4103831,2.17,3.31,Authoritarian,14.3,Denis Sassou Nguesso,President
39,Côte d'Ivoire,Republic of Côte d'Ivoire,West African CFA franc,Yamoussoukro,Western Africa,Africa,Ivorian,8.000000,-5.000000,212000.0,28367.1,318000.0,318024.000,2981.9600,171.06500,16.601700,7.001870e+10,5.27617,72.5864,12.559100,2.637,71.0193,71.13680,0.794777,0.000000,15.520600,78.050700,0.0000,5.223280,1.205370,7.07754,26.49230,63.34,10894.900,7980.3700,3544.21000,2083.5100,2.719800,3.72246,85.1743,0.40,0.21,8.9,134000.0,302000.0,1.251480,33.934,9.001,4.418,45.42550,59.0,-21000,13944972,14215570,28160542,14.17320,13330919,14829623,2.65,4.15,Hybrid regime,13.8,Alassane Ouattara,President
45,Dem. Rep. Congo,Democratic Republic of the Congo,Congolese franc,Kinshasa,Middle Africa,Africa,Congolese,0.000000,25.000000,335720.0,1261550.0,2267050.0,2295900.000,7232.3500,152.18700,11.498300,5.806600e+10,2.88585,80.6942,10.704100,4.987,78.1651,20.76820,2.359950,0.000000,99.709200,0.044733,0.0000,0.134198,0.111832,1.95927,5.35581,96.16,3025.600,35684.2000,14960.60000,-2774.7700,0.003635,4.05093,21.2539,0.80,0.18,6.7,134000.0,5686000.0,0.561686,42.049,9.700,6.156,22.90160,59.0,-64643,49892177,49118035,99010212,12.80000,52636799,46373413,1.51,1.49,Authoritarian,11.7,Félix Tshisekedi,President
47,Djibouti,Republic of Djibouti,Djibouti franc,Djibouti,Eastern Africa,Africa,Djibouti,11.500000,43.000000,17020.0,58.0,23180.0,21571.800,51.2502,NaN,NaN,3.515110e+09,5.17981,51.4098,NaN,27.929,47.0314,65.44130,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00000,30.94,427.700,659.9230,259.18300,-988.8510,8.609440,2.00786,62.8094,1.40,0.13,9.6,13000.0,NaN,3.688070,22.205,9.147,2.804,68.86320,62.0,742,564584,556264,1120849,26.15380,242328,878521,1.10,2.87,Authoritarian,20.0,Ismaïl Omar Guelleh,President
51,Egypt,Arab Republic of Egypt,Egyptian pound,Cairo,Northern Africa,Africa,Egyptian,27.000000,30.000000,39710.0,449.8,995450.0,971206.000,18918.0000,85.78850,30.230400,4.767480e+11,13.89570,27.1192,12.519200,6.959,18.1332,100.00000,1.499720,0.000000,7.381150,70.728700,0.0000,21.012000,0.878133,-7.39149,97.92890,6.51,210752.000,64402.9000,20471.50000,17962.6000,13.750900,4.36498,150.9070,1.43,NaN,3.0,836000.0,3200.0,1.300820,22.558,6.327,2.917,72.06000,70.0,-32370,54865512,56124592,110990103,27.58040,63300985,47689118,1.38,3.36,Authoritarian,20.1,Abdel Fattah el-Sisi,President
53,Equatorial Guinea,Republic of Equatorial Guinea,Central African CFA franc,Malabo,Middle Africa,Africa,Equatorial Guinean,2.000000,10.000000,1885.2,24484.2,28050.0,26898.200,136.7340,NaN,10.312700,1.181390e+10,4.78672,87.7860,5.371570,8.689,79.2595,66.78700,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00000,5.99,4350.400,4778.3200,33.33930,3703.6300,4.902130,3.76834,236.6200,2.10,3.80,7.9,1000.0,NaN,1.305170,30.498,9.042,4.266,53.92240,61.0,6486,790982,883926,1674908,31.00000,435309,1239599,1.34,1.92,Authoritarian,16.8,Teodoro Obiang Nguema Mbasogo,President
54,Eritrea,State of Eritrea,Eritrean nakfa,Asmara,Eastern Africa,Africa,Eritrean,15.000000,39.000000,75920.0,10552.6,121041.0,120001.000,331.1920,NaN,NaN,2.065000e+09,NaN,86.8692,NaN,6.618,85.6159,52.51400,0.021121,0.000000,0.000000,0.000000,0.0000,99.507400,0.492611,22.26720,23.13340,80.90,706.400,3732.2400,1730.46000,35.8599,14.903800,4.09360,23.9813,0.70,0.06,10.9,202000.0,10000.0,20.865700,28.624,6.729,3.867,21.73040,67.0,-14988,1866154,1817878,3684032,22.00000,2113713,1570319,0.97,2.37,Authoritarian,14.5,Isaias Afwerki,President
56,Eswatini,Kingdom of Eswatini,Swazi lilangeni,Lobamba,Southern Africa,Africa,Swazi,-26.500000,31.500000,12220.0,4975.6,17200.0,17073.200,177.9190,NaN,NaN,4.854170e+09,2.59802,34.0519,NaN,24.389,32.0574,82.90320,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00000,68.77,1147.700,1326.0300,423.54500,642.4280,0.000000,6.51153,219.1040,2.10,7.65,29.4,3000.0,NaN,1.698020,24.134,11.356,2.839,58.91290,57.0,-4897,605504,596167,1201670,13.51350,906348,295322,1.59,3.03,Authoritarian,17.7,Mswati III,King
57,Ethiopia,Federal Democratic Republic of Ethiopia,Ethiopian birr,Addis Ababa,Eastern Africa,Africa,Ethiopian,8.000000,38.000000,384761.0,170685.0,1128570.0,1124620.000,5760.6600,31.44880,8.412270,1.267830e+11,26.83950,85.6278,6.196300,4.018,85.1910,54.18840,1.183670,0.000000,92.689500,0.000000,0.0000,0.038325,7.272200,5.92631,6.56981,89.52,18098.000,94645.6000,53761.30000,5071.1400,0.000000,3.48096,28.6967,0.33,0.12,5.4,138000.0,3852000.0,0.527828,32.383,6.776,4.159,16.69810,65.0,-1391,61399749,61980175,123379924,41.48940,95420799,27959125,2.23,3.35,Authoritarian,14.7,Abiy Ahmed,Prime Minister
61,Gabon,Gabonese Republic,Central African CFA franc,Libreville,Middle Africa,Africa,Gabonese,-1.000000,11.750000,22126.4,235306.0,257670.0,263338.000,311.6000,NaN,13.541900,2.107170e+10,4.23125,33.6156,11.479500,21.469,31.1541,91.80640,1.212100,0.000000,43.179700,46.048900,0.0000,10.207000,0.564440,-213.40100,22.78650,90.12,5349.200,7451.5600,523.12200,1095.7900,7.881840,3.42725,228.9760,6.30,0.80,8.4,7000.0,NaN,1.710040,27.142,7.258,3.491,71.74940,66.0,1516,1173488,1215505,2388992,15.38460,221340,2167652,2.20,3.61,Authoritarian,17.7,Ali Bongo Ondimba,President
64,Ghana,Republic of Ghana,New Ghanaian cedi,Accra,Western Africa,Africa,Ghanaian,8.000000,-2.000000,126037.0,79857.1,227533.0,227830.000,5559.5500,NaN,21.883600,7.283880e+10,31.25590,75.0451,11.340400,3.867,69.8307,86.30000,5.868650,0.000000,50.865900,38.847800,0.0000,0.000000,0.026107,-8.19210,52.54310,40.25,19401.200,11847.9000,6369.12000,680.0140,1.415630,3.99030,84.9784,0.90,0.57,6.6,16000.0,5000.0,0.492101,27.548,7.627,3.563,68.20000,64.0,-11253,16780756,16695114,33475870,14.54550,13853989,19621881,3.76,6.63,Flawed democracy,16.6,Nana Akufo-Addo,President
68,Guinea,Republic of Guinea,Guinean franc,Conakry,Western Africa,Africa,Guinean,11.000000,-10.000000,145000.0,61890.0,245720.0,244206.000,1390.6600,NaN,9.433050,2.122770e+10,10.49300,92.6106,10.841800,5.749,91.2606,46.81390,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,65.53,4537.900,16813.3000,6822.44000,1868.2000,1.469060,4.04451,46.8419,0.30,0.49,7.0,13000.0,NaN,1.484540,34.425,9.990,4.399,34.68010,59.0,-4367,7005320,6854020,13859341,29.62960,8638804,5220537,2.34,3.14,Authoritarian,13.9,Alpha Condé,President
69,Guinea-Bissau,Republic of Guinea-Bissau,West African CFA franc,Bissau,Western Africa,Africa,Guinea-Bissauan,12.000000,-15.000000,8151.1,19800.1,28120.0,33293.400,196.2640,NaN,14.646600,1.633560e+09,9.39384,82.3292,9.462070,3.583,81.1754,35.76380,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00000,87.26,329.000,1261.1200,765.86100,111.2940,1.240850,8.40979,61.4319,1.00,1.12,7.0,4000.0,NaN,1.782640,31.087,8.716,4.005,35.15500,60.0,-1395,1065706,1039860,2105566,13.72550,1157198,948368,2.53,1.98,Authoritarian,14.5,Umaro Sissoco Embaló,President
86,Kenya,Republic of Kenya,Kenyan shilling,Nairobi,Eastern Africa,Africa,Kenyan,1.000000,38.000000,276300.0,36110.9,569140.0,579896.000,3416.8400,NaN,20.706300,1.134200e+11,7.65687,62.0530,13.264900,5.502,60.5601,76.54240,2.238940,0.000000,39.239500,0.000000,0.0000,12.485800,48.274800,17.16990,17.37960,72.50,19446.800,37602.5000,20969.00000,3975.0800,0.210684,4.29191,83.3962,1.40,0.73,6.1,29000.0,30000.0,1.119110,27.685,8.056,3.335,28.75750,61.0,-52549,27249938,26777549,54027487,23.42860,38358435,15669052,2.41,5.11,Hybrid regime,15.4,Uhuru Kenyatta,President
94,Lesotho,Kingdom of Lesotho,Lesotho loti,Maseru,Southern Africa,Africa,Mosotho,-29.500000,28.500000,26000.0,345.2,30360.0,30172.300,249.9420,2.90222,38.726800,2.553460e+09,8.27180,54.9118,32.390100,18.039,52.0954,50.37750,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00000,32.29,2311.900,998.8280,537.86300,2061.5600,0.000000,11.78430,107.0990,1.30,4.76,72.4,2000.0,NaN,1.287190,26.107,14.186,3.018,47.98300,53.0,-1490,1168329,1137496,2305825,26.44630,1615392,690433,2.63,6.64,Flawed democracy,18.2,Tom Thabane,Prime Minister
95,Liberia,Republic of Liberia,U.S. dollar,Monrovia,Western Africa,Africa,Liberian,6.500000,-9.500000,19540.4,76174.4,96320.0,95557.600,652.5560,20.31800,NaN,4.001050e+09,23.56350,80.5154,12.461400,3.634,78.9296,29.84820,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,92.94,1179.500,338.8690,295.30200,803.3420,9.521250,9.49941,56.7061,0.80,NaN,4.5,2000.0,23000.0,0.951295,31.287,8.838,4.089,33.63320,61.0,-11862,2661979,2640702,5302681,10.95890,2488813,2813868,2.48,5.35,Hybrid regime,14.2,George Weah,President
96,Libya,Socialist People's Libyan Arab Jamahiriya,Libyan dinar,Tripoli,Northern Africa,Africa,Libyan,25.000000,17.000000,153500.0,2170.0,1759540.0,1619020.000,2958.1500,NaN,NaN,4.575230e+10,2.60582,29.2568,NaN,20.680,26.4948,70.21050,0.000000,0.000000,0.000000,53.700300,0.0000,46.299700,0.000000,-102.96400,99.11130,3.12,44467.000,24033.1000,1797.65000,2093.9300,5.795390,6.05013,312.8490,3.20,0.07,4.5,0.0,135000.0,15.479600,17.828,6.018,2.462,17.76000,72.0,-696,3365279,3447062,6812341,16.47060,1273772,5538569,1.40,2.19,Authoritarian,22.6,Fayez al-Sarraj,Prime Minister
100,Madagascar,Republic of Madagascar,Malagasy ariary,Antananarivo,Eastern Africa,Africa,Malagasy,-20.000000,47.000000,408950.0,124298.0,581800.0,588613.000,1660.5900,NaN,10.543200,1.495500e+10,8.16059,89.2849,10.238500,2.142,84.3329,35.12090,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,83.63,2745.450,19021.9000,7665.37000,993.9530,2.099090,3.87958,17.9457,0.20,0.35,5.5,22000.0,2800.0,0.770034,30.949,7.104,3.851,19.73020,64.0,-742,14775496,14836218,29611714,18.54300,17801970,11809744,2.82,5.22,Hybrid regime,15.1,Andry Rajoelina,President
101,Malawi,Republic of Malawi,Malawi kwacha,Lilongwe,Eastern Africa,Africa,Malawian,-13.500000,34.000000,56500.0,22417.0,94280.0,93702.800,770.8610,44.89330,16.881300,1.316470e+10,20.95400,61.3774,11.381600,5.614,59.9534,14.18840,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,75.17,1640.000,4389.7000,5054.86000,174.4020,0.000000,5.43400,32.9825,1.30,1.13,5.4,15000.0,NaN,0.948970,32.859,6.983,3.917,24.40560,63.0,-1775,10480456,9924861,20405317,22.91670,16736441,3668876,2.66,5.49,Hybrid regime,13.1,Peter Mutharika,President
104,Mali,Republic of Mali,West African CFA franc,Bamako,Western Africa,Africa,Malian,17.000000,-4.000000,412010.0,132960.0,1220190.0,1251580.000,1505.0200,NaN,14.501100,1.882720e+10,3.92560,81.3281,14.164500,2.762,80.7116,53.38020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,63.76,4150.700,23070.5000,15086.90000,3643.5800,0.000000,4.30812,35.4516,0.10,0.26,4.1,21000.0,380000.0,2.821950,41.643,9.274,5.956,34.49000,59.0,-22236,11186771,11406819,22593590,28.57140,12327741,10265849,2.22,5.41,Hybrid regime,11.3,Ibrahim Boubacar Keïta,President
107,Mauritania,Islamic Republic of Mauritania,Mauritanian ouguiya,Nouakchott,Western Africa,Africa,Mauritanian,20.000000,-12.000000,396610.0,3128.0,1030700.0,1045550.000,373.5390,NaN,NaN,1.037550e+10,9.52527,56.9632,NaN,11.109,53.0474,47.69580,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23.44,3847.100,6896.7500,3273.34000,275.6550,19.539800,3.35573,59.0492,0.40,0.13,3.1,21000.0,NaN,2.378160,33.194,7.440,4.398,58.75820,64.0,-1494,2414911,2321228,4736139,20.26140,2040187,2695952,2.47,3.82,Authoritarian,13.8,Mohamed Ould Ghazouani,President
108,Mauritius,Republic of Mauritius,Mauritian rupee,Port Louis,Eastern Africa,Africa,Mauritian,-20.283333,57.550000,860.0,387.7,2030.0,1523.760,475.8040,57.96170,32.959700,1.289830e+10,10.77380,18.8076,18.277000,7.234,15.8346,99.60000,0.804578,39.439400,4.070740,0.000000,0.0000,37.837800,18.652000,84.54230,84.54240,9.41,3720.200,1973.7300,221.86900,1217.6900,1.186910,6.65996,560.4060,3.40,0.54,9.5,3000.0,NaN,0.169558,10.300,10.500,1.410,67.58000,74.0,-478,639989,622533,1262523,20.00000,747287,515236,2.75,8.22,Full democracy,33.1,Pravind Jugnauth,Prime Minister
115,Morocco,Kingdom of Morocco,Moroccan dirham,Rabat,Northern Africa,Africa,Moroccan,32.000000,-5.000000,303820.0,57424.9,446300.0,409516.000,4621.3500,51.22630,25.479300,1.341820e+11,6.65704,47.9136,19.549000,10.494,45.6347,100.00000,1.616760,55.525600,6.116160,18.767000,0.0000,7.173910,8.192730,90.72180,88.46890,10.92,66719.500,12029.8000,8693.63000,5825.5400,1.169120,5.99316,187.4040,1.00,0.02,7.2,246000.0,NaN,4.183510,17.545,6.170,2.328,88.13030,74.0,-46242,18605603,18852368,37457971,24.05060,13261620,24196351,1.78,4.99,Hybrid regime,25.0,Mohammed VI,King